version: '3.8'

services:
  neovim-dev:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        - USERNAME=vscode
        - USER_UID=1000
        - USER_GID=1000

    # Keep container running
    stdin_open: true
    tty: true

    # Run as non-root user
    user: vscode

    volumes:
      # Mount current directory as workspace
      - .:/workspace:cached

      # Mount Docker socket for Docker-in-Docker (Wrangler needs this)
      - /var/run/docker.sock:/var/run/docker.sock

      # Optional: Mount SSH keys for git operations
      - ~/.ssh:/home/vscode/.ssh:ro

      # Optional: Mount AWS credentials
      # - ~/.aws:/home/vscode/.aws:ro

      # Optional: Persist Neovim plugins and config between containers
      # - nvim-data:/home/vscode/.local/share/nvim
      # - nvim-config:/home/vscode/.config/nvim

    working_dir: /workspace

    # Load environment variables from .env file
    env_file:
      - .env

    environment:
      # Override or add environment variables
      - TERM=xterm-256color
      - COLORTERM=truecolor
      - SHELL=/bin/bash

    # Network mode - uncomment if you need to access local services
    # network_mode: host

    command: /bin/bash -c "bash .devcontainer/post-create.sh && exec bash"

# Optional: Named volumes for persistence
volumes:
  nvim-data:
  nvim-config: